### ISSUE TITLE
No preview image on social platforms

### ISSUE THREAD

**Issue by za158** [georgetown-cset/eto-orca#265]
eg linkedin - 
![image](https://github.com/georgetown-cset/github-metrics/assets/58824955/d6d8b7ab-e1a7-470e-9c46-cb6e90741b2c)

**Comment by brianlove** [comment]
"Fun" fact: Updating UI Components to 1.6.0 or later causes several of the `dashboard.test.js` tests to fail....  This is happening even after updating all the (other) dependencies that I can think, so something about the Dropdown/Autocomplete overhaul in that release has caused problems

**Comment by brianlove** [comment]
I've decoupled `@eto/social-cards` and `@eto/eto-ui-components`, so this isn't blocking the addition of social cards anymore, but ORCA is still currently limited to UIC 1.5.3, not 1.6.x.  Tracking in #303
